### ISSUE TITLE
MMM-PIR-Sensor-Lite not closing complete screen

### ISSUE THREAD

**Issue by DennisEJ** [grenagit/MMM-PIR-Sensor-Lite#1]
First of all let me say i LOVE the app.  It was the easiest of all I tried to install and worked the first time...  Just amazing..
The one problem I am having is that it blanks the MagicMirror screen but doesn't blank the primary screen.  It still says "no signal" and has a square that the message is in.. I'm sure I missed something on the install but I looked through the options and didn't see anything that would help... Anyone know what I missed?
Thanks
Dennis

**Comment by sdetweil** [comment]
@DennisEJ 

the command used vcgencmd  turns off the HDMI port. and then the energy-star compliant monitors/tv's MUST output the no-input warning.. (and turn of after 15 minutes)..

NEWER Monitors provide support for the CEC command set (Consumer Electronics Communication)  which will allow programmatic  access to turn off/on the display .    it doesn't work on my pi3 , but does on my pi 4.. EXCEPT 

my TV which says it DOES support cec commands I can turn on, but not off...!?

sudo apt install  cec-utils
then see the cec-client --help for info.
IF your system and monitor support it,  then it could be used instead of vcgencmd 

here is a script i maintain for another mirror platform that does all 4 ways..
https://github.com/sdetweil/smart-mirror/blob/master/scripts/raspi-monitor.sh
edit the type to be 'cec-utils'
```
type=vcgencmd
```
(make the script executable)
then ./raspi-monitor.sh on (or off)

**Comment by DennisEJ** [comment]
Thanks again Sam
I’ll try it
